# Generated by Django 4.1.3 on 2023-02-01 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="username",
        ),
    ]
