# Generated by Django 4.1.3 on 2023-01-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_phone_customer_rename_name_customer_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
