# Generated by Django 4.1.3 on 2022-12-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_size_remove_product_price_productvariants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
