# Generated by Django 4.1.3 on 2023-01-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_price_alter_size_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_category',)},
        ),
    ]
