# Generated by Django 4.1.3 on 2022-12-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_delete_pizza'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
