# Generated by Django 4.1.3 on 2023-01-18 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-product_category',)},
        ),
    ]
