# Generated by Django 4.1.3 on 2023-01-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
