# Generated by Django 4.1.3 on 2022-12-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
