# Generated by Django 4.1.3 on 2023-01-04 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_delivery_method_order_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUpDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency', models.CharField(choices=[('asap', 'asap'), ('custom', 'custom')], max_length=10)),
                ('pickup_date', models.DateTimeField()),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
