# Generated by Django 4.1.3 on 2023-01-31 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.PositiveIntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pickupdetail',
            name='pickup_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
