# Generated by Django 4.1.3 on 2023-01-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_pickupdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupdetails',
            name='email',
            field=models.EmailField(default='vasya@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickupdetails',
            name='phone',
            field=models.CharField(default='12345', max_length=20),
            preserve_default=False,
        ),
    ]
