# Generated by Django 4.1.3 on 2022-12-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
