# Generated by Django 4.1.3 on 2023-01-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_pickupdetails_pickupdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupdetail',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
