# Generated by Django 4.1.3 on 2023-01-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_pickupdetail_pickup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupdetail',
            name='pickup_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
