# Generated by Django 4.1.3 on 2023-01-04 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_pickupdetail_pickup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupdetail',
            name='pickup_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
