# Generated by Django 4.1.3 on 2023-01-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_pickupdetail_pickup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='stripe_api_id',
        ),
    ]
