# Generated by Django 4.1.3 on 2022-12-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_coupon_stripe_api_id_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
