# Generated by Django 4.1.3 on 2023-01-10 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_shippingaddress_order_order_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupdetail',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.pickupdetail'),
        ),
    ]
