# Generated by Django 4.1.3 on 2023-01-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_email_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupdetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pickupdetail',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='phone',
        ),
    ]
