# Generated by Django 4.1.3 on 2023-01-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_remove_pickupdetail_email_remove_pickupdetail_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
